### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by cereallarceny** [cereallarceny/cra-ssr#61]
**To summarize, I'm doing a total rewrite of `cra-ssr` to bring it up to date with the latest the React community has to offer.**

**_This is to be considered a living document. I'm taking suggestions on features you'd like to see, comment below!_**

### Features (most of which already exist):
- [ ] Rewrite to be used as a dev dependency
- [ ] Use with any React project, including CRA and others
- [ ] Rebrand to not be tied to Create React App
- [ ] Support code splitting
- [ ] Support for hooks
- [ ] Support variety of CSS in JS
- [ ] Support CSS preprocessors (https://github.com/cereallarceny/cra-ssr/issues/60)
- [ ] Support static asset serving (svg, png, jpg, webp, etc.) (https://github.com/cereallarceny/cra-ssr/issues/58, https://github.com/cereallarceny/cra-ssr/issues/56)
- [ ] Support for relative and absolute URLS (https://github.com/cereallarceny/cra-ssr/issues/57)
- [ ] Support for any state management library (Redux, Mobx, Redux Sagas) (https://github.com/cereallarceny/cra-ssr/issues/34, https://github.com/cereallarceny/cra-ssr/issues/35)
- [ ] Support for cookies
- [ ] Custom data loading (with or without `react-frontload`)
- [ ] Add support for some components to skip server-side rendering (https://github.com/cereallarceny/cra-ssr/issues/54)
- [ ] CLI interface for converting existing projects (if necessary)
- [ ] Support ejection, but don't make it mandatory (https://github.com/cereallarceny/cra-ssr/issues/51)
- [ ] Add `isServer` flag to help front-end libraries know when it's safe to use `window` (https://github.com/cereallarceny/cra-ssr/issues/44)

### Bugs to keep in mind:
https://github.com/cereallarceny/cra-ssr/issues/53

**Comment by cereallarceny** [comment]
# Deprecation notice

It didn't take long.  The web has grown a lot since I first developed this project.  Lo and behold @jaredpalmer has beat me to it.  I'm going to shut down shop at cra-ssr in favor of a better solution: [Razzle](https://github.com/jaredpalmer/razzle).

**To anyone looking to use cra-ssr, I highly suggest you check out Razzle instead.**

**Comment by hugominas** [comment]
Thank you for all the work @cereallarceny, I have used cra-ssr in many projects. Lately I have been using [react-snap](https://github.com/stereobooster/react-snap) but I will definitely look into Razzle.

**Comment by microcipcip** [comment]
@cereallarceny that's a pity, I chose cra-ssr over razzle as it was very straightforward to understand what was happening in the background, thanks for your awesome project anyway :)

**Comment by cereallarceny** [comment]
Thank you for your support @hugominas and @microcipcip!  Of course, I'll leave the repo online.  If Razzle isn't your thing, you might want to check out [CRA Universal](https://github.com/antonybudianto/cra-universal).  It's a similar approach to cra-ssr.  Likewise, I suggest you check out Razzle again - it's seemingly identical to what I intended to do for version 2 of cra-ssr.

**Comment by harrison0723** [comment]
I honestly like cra-ssr over razzle, the latter has too many things under the hood that made my other integrations a pain in the ass (i.e. Ant Design, etc.)

**Comment by cereallarceny** [comment]
I was likely going to take a nearly identical approach anyhow @harrison0723, but I appreciate the kind words!
